### ISSUE TITLE
SyntaxError: Unexpected token '?' with Node.js v20.6.1

### ISSUE THREAD

**Issue by juliankasimir** [sindresorhus/find-up-simple#2]
Hi,

I'm encountering an issue with `find-up-simple` when using it in combination with [Lefthook](https://www.npmjs.com/package/lefthook) and [cspell](https://cspell.org/) under Node.js v20.6.1. The error message is as follows:

```
(...)/node_modules/find-up-simple/index.js:14
	let directory = path.resolve( toPath( cwd ) ? ? '' );
	                                              ^
SyntaxError: Unexpected token '?'
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:118:18)
    at callTranslator (node:internal/modules/esm/loader:265:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:270:30)
Node.js v20.6.1
```

### Reproduction Steps

1. **Setup Lefthook**:
   Create a `lefthook.yml` configuration with the following `commit-msg` hook:

   ```yaml
   commit-msg:
     parallel: true
     commands:
       lint-commit-msg:
         run: npx commitlint --edit
       spell-check:
         run: npx cspell --locale=en --no-summary --no-progress --show-suggestions --language-id commit-msg {1}
   ```

2. **Install Dependencies**:
   Ensure you have `commitlint`, `cspell`, and `lefthook` installed as dependencies.

3. **Run Lefthook**:
   Make a commit that triggers the `commit-msg` hook.

### Issue Details

The above setup leads to the following error due to the use of optional chaining (`? ?`) in `find-up-simple`:

```
SyntaxError: Unexpected token '?'
```

It seems like this might be a compatibility issue with the latest Node.js version. Could you please investigate and advise on how to resolve this?

Thank you!
